name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Provision Gradle 8.7
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Gasto-Ituzaingo-APK
          path: app/build/outputs/apk/debug/*.apk

